# Operaciones por capas

In [1]:
import tensorflow as tf
import numpy as np

- $X \in \mathbb R_{3\times 4} $

In [2]:
session = tf.Session()

In [4]:
my_array = np.array([[1.,3.,5.,7.],[-2,.0,7.,6.],[-6.,-1.,0.,3.]])
my_array

array([[ 1.,  3.,  5.,  7.],
       [-2.,  0.,  7.,  6.],
       [-6., -1.,  0.,  3.]])

In [5]:
x_vals = np.array([my_array, my_array+1])
x_vals

array([[[ 1.,  3.,  5.,  7.],
        [-2.,  0.,  7.,  6.],
        [-6., -1.,  0.,  3.]],

       [[ 2.,  4.,  6.,  8.],
        [-1.,  1.,  8.,  7.],
        [-5.,  0.,  1.,  4.]]])

In [6]:
x_data = tf.placeholder(tf.float32, shape={3,4})

- $m_1 \in \mathbb R^4 $
- $m_2,a_1 \in \mathbb R $

In [13]:
m1 = tf.constant([[1.],[0.],[-2.],[5.]])
m2 = tf.constant([[7.]])
a1 = tf.constant([[15.]])

$$ (X\cdot m_1)m_2+a_1$$

In [15]:
eq_res = tf.matmul(tf.matmul(x_data,m1),m2)
eq_res = tf.add(eq_res,a1)

In [16]:
for x_val in x_vals:
    print(session.run(eq_res, feed_dict={x_data:x_val}))

[[197.]
 [113.]
 [ 78.]]
[[225.]
 [141.]
 [106.]]
